<a href="https://colab.research.google.com/github/AkankshaB123/python/blob/main/ConfirmationRate_CaseWhen(Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

signups = pd.DataFrame( {
    "user_id" : [3,7,2,6],
    "time_stamp" : ["2020-03-21 10:16:13", "2020-01-04 13:57:59", "2020-07-29 23:09:44", "2020-12-09 10:39:37"]}
)

confirmations = pd.DataFrame({
    "user_id" : [3,3,7,7,7,2,2],
    "time_stamp" : ["2021-01-06 03:30:46","2021-07-14 14:00:00","2021-06-12 11:57:29","2021-06-13 12:58:28","2021-06-14 13:59:27","2021-01-22 00:00:00","2021-02-28 23:59:59"],
    "action" : ["timeout","timeout","confirmed","confirmed","confirmed","confirmed","timeout"]
})

In [36]:
def confirmation_rate(signups: pd.DataFrame, confirmations: pd.DataFrame) -> pd.DataFrame:
  df = pd.merge(left = signups['user_id'], right = confirmations[['user_id','action']], how='left', on='user_id')
  df['flag'] = 0
  df.loc[df['action'] == 'confirmed', 'flag'] = 1 #Logic for new column
  df['flag1'] = df['flag']
  return df.groupby('user_id').agg({'flag':'count','flag1':'sum'}).reset_index()
  # df['confirmation_rate'] = df['flag1']/df['flag'].round(2)

In [37]:
confirmation_rate(signups, confirmations)

   user_id  flag  flag1
0        2     2      1
1        3     2      0
2        6     1      0
3        7     3      3

In [45]:
def confirmation_rate(signups: pd.DataFrame, confirmations: pd.DataFrame) -> pd.DataFrame:
  df = pd.merge(left = signups['user_id'], right = confirmations[['user_id','action']], how='left', on='user_id')
  df['flag'] = 0
  df.loc[df['action'] == 'confirmed', 'flag'] = 1 #Logic for new column
  df['flag1'] = df['flag']
  #View the correction
  df.groupby('user_id').agg({'flag':'count','flag1':'sum'}).reset_index()
  df['confirmation_rate'] = df['flag1']/df['flag'].round(2)
  return df[['user_id','confirmation_rate']]

In [46]:
confirmation_rate(signups, confirmations)

   user_id  confirmation_rate
0        3                NaN
1        3                NaN
2        7                1.0
3        7                1.0
4        7                1.0
5        2                1.0
6        2                NaN
7        6                NaN

In [52]:
def confirmation_rate(signups: pd.DataFrame, confirmations: pd.DataFrame) -> pd.DataFrame:
  df = pd.merge(left = signups['user_id'], right = confirmations[['user_id','action']], how='left', on='user_id')
  df['flag'] = 0
  df.loc[df['action'] == 'confirmed', 'flag'] = 1 #Logic for new column
  df['flag1'] = df['flag']
  #View the correction
  df = df.groupby('user_id').agg({'flag':'count','flag1':'sum'}).reset_index()
  df['confirmation_rate'] = (df['flag1']/df['flag']).round(2).apply(lambda x: '{:.2f}'.format(x))
  return df[['user_id','confirmation_rate']]

In [53]:
confirmation_rate(signups, confirmations)

   user_id confirmation_rate
0        2              0.50
1        3              0.00
2        6              0.00
3        7              1.00