<a href="https://colab.research.google.com/github/AkankshaB123/python/blob/main/Functions_Revision_Python_SQL_50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd

data = {
    'article_id': [1, 1, 2, 2, 4, 3, 3],
    'author_id': [3, 3, 7, 7, 7, 4, 4],
    'viewer_id': [5, 6, 7, 6, 1, 4, 4],
    'view_date': ['2019-08-01', '2019-08-02', '2019-08-01', '2019-08-02', '2019-07-22', '2019-07-21', '2019-07-21']
}
df = pd.DataFrame(data)

# Convert 'view_date' to datetime objects
df['view_date'] = pd.to_datetime(df['view_date'])

In [34]:
display(df.head())

   article_id  author_id  viewer_id  view_date
0           1          3          5 2019-08-01
1           1          3          6 2019-08-02
2           2          7          7 2019-08-01
3           2          7          6 2019-08-02
4           4          7          1 2019-07-22

# Article Views I

## Q1. Write a solution to find all the authors that viewed at least one of their own articles

Return the result table sorted by id in ascending order

In [13]:
import pandas as pd

def article_views(views:pd.DataFrame) -> pd.DataFrame:
    df = views[views['author_id'] == views['viewer_id']]
    df = df[['author_id']].drop_duplicates().sort_values('author_id').rename(columns={'author_id':'id'})
    return df

In [14]:
article_views(df)

   id
5   4
2   7

# Invalid Tweeets

## Q2. Solution to find IDs of the invalid tweets. The tweet is invalid if the no of characters used in the content of the tweet is strictly greater than 15.

In [35]:
data_tweets = {
    'tweet_id': [1, 2],
    'content': ['Let us Code', 'More than fifteen chars are here!']
}
tweets_df = pd.DataFrame(data_tweets)

display(tweets_df.head())

   tweet_id                            content
0         1                        Let us Code
1         2  More than fifteen chars are here!

In [18]:
def invalid_teets(tweets: pd.DataFrame) -> pd.DataFrame:
  df = tweets
  fc = df['content'].str.len()
  return df[fc>15][['tweet_id']]

In [19]:
invalid_teets(tweets_df)

   tweet_id
1         2

# Q3. Customers Who Visited but Did Not Make Any Transaction  - 2 dataframes

In [36]:
visits_data = {
    'visit_id': [1, 2, 4, 5, 6, 7, 8],
    'customer_id': [23, 9, 30, 54, 96, 54, 54]
}
visits_df = pd.DataFrame(visits_data)

display(visits_df.head())

   visit_id  customer_id
0         1           23
1         2            9
2         4           30
3         5           54
4         6           96

In [37]:
transactions_data = {
    'transaction_id': [2, 3, 9, 12, 13],
    'visit_id': [5, 5, 5, 1, 2],
    'amount': [310, 300, 200, 910, 970]
}
transactions_df = pd.DataFrame(transactions_data)

display(transactions_df.head())

   transaction_id  visit_id  amount
0               2         5     310
1               3         5     300
2               9         5     200
3              12         1     910
4              13         2     970

In [45]:
def find_customers(visits: pd.DataFrame, transactions: pd.DataFrame) -> pd.DataFrame:
    df1 = visits_df
    df2 = transactions_df

    df = df1.merge(df2, on='visit_id', how='left')
    fc = df['transaction_id'].isnull()
    return df[fc].groupby('customer_id').agg({'visit_id':'count'}).reset_index().rename(columns={'visit_id':'count_no_trans'})

In [47]:
display(find_customers(visits_df,transactions_df))

   customer_id  count_no_trans
0           30               1
1           54               2
2           96               1

# Q4. Rising Temperature

In [52]:
weather_data = {
    'id': [1, 2, 3, 4],
    'recordDate': ['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04'],
    'temperature': [10, 25, 20, 30]
}
weather_df = pd.DataFrame(weather_data)

# Convert 'recordDate' to datetime objects
weather_df['recordDate'] = pd.to_datetime(weather_df['recordDate'])

display(weather_df.head())

   id recordDate  temperature
0   1 2015-01-01           10
1   2 2015-01-02           25
2   3 2015-01-03           20
3   4 2015-01-04           30

In [63]:
def rising_temperature(weather: pd.DataFrame) -> pd.DataFrame:
    df = weather
    df.sort_values('recordDate', inplace=True) #very crucial point
    df['prev_temp'] = df['temperature'].shift(1) # prev_value
    df['prev_date'] = df['recordDate'].shift(1)
    return df[(df['temperature'] > df['prev_temp']) & ((df['recordDate'] - df['prev_date']) == 1)][['id']]

In [62]:
rising_temperature(weather_df)

   id recordDate  temperature  prev_temp  prev_date
0   1 2015-01-01           10        NaN        NaT
1   2 2015-01-02           25       10.0 2015-01-01
2   3 2015-01-03           20       25.0 2015-01-02
3   4 2015-01-04           30       20.0 2015-01-03

* Fix 1: inplace = True
* Fix 2: Handle gaps explicit mention of recordDate - prevDate = 1

In [64]:
rising_temperature(weather_df)

Empty DataFrame
Columns: [id]
Index: []

Output is 0, 14 is there and 16 is there because previous date nothing is there. This is the output test-case.

# **Important Question 5.) Average Time of Process per Machine**

In [65]:
activity_data = {
    'machine_id': [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2],
    'process_id': [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
    'activity_type': ['start', 'end', 'start', 'end', 'start', 'end', 'start', 'end', 'start', 'end', 'start', 'end'],
    'timestamp': [0.712, 1.520, 3.140, 4.120, 0.550, 1.550, 0.430, 1.420, 4.100, 4.512, 2.500, 5.000]
}
activity_df = pd.DataFrame(activity_data)

display(activity_df.head())

   machine_id  process_id activity_type  timestamp
0           0           0         start      0.712
1           0           0           end      1.520
2           0           1         start      3.140
3           0           1           end      4.120
4           1           0         start      0.550

* Approach 1: Self-Join to split into 2 tables
* Approach 2: LAG or Shift(1) to get previous value
* Approach 3:

In [83]:
def get_averages(activity: pd.DataFrame) -> pd.DataFrame:
    df = activity
    start_df = df[df['activity_type'] == 'start']
    end_df = df[df['activity_type'] == 'end']
    final_df = pd.merge(start_df,end_df, on = ['machine_id','process_id'], how = 'inner')
    final_df['processing_time'] = final_df['timestamp_y'] - final_df['timestamp_x']
    final_df = final_df.groupby('machine_id').agg({'processing_time':'mean'}).reset_index().round(3)
    return final_df

In [76]:
get_averages(activity_df)

,machine_id,process_id,activity_type_x,timestamp_x,activity_type_y,timestamp_y,processing_time
0,0,0,start,0.712,end,1.520,0.808
1,0,1,start,3.140,end,4.120,0.980
2,1,0,start,0.550,end,1.550,1.000
3,1,1,start,0.430,end,1.420,0.990
4,2,0,start,4.100,end,4.512,0.412
5,2,1,start,2.500,end,5.000,2.500

In [84]:
get_averages(activity_df)

   machine_id  processing_time
0           0            0.894
1           1            0.995
2           2            1.456

### Q6. Students and Examination (Solved using Cross Join) - Important Question (Already Solved - Refer to Github)

# Q7. Manager with 5 Direct Reports

In [85]:
employee_data = {
    'id': [101, 102, 103, 104, 105, 106],
    'name': ['John', 'Dan', 'James', 'Amy', 'Anne', 'Ron'],
    'department': ['A', 'A', 'A', 'A', 'A', 'B'],
    'managerId': [None, 101, 101, 101, 101, 101]
}
employee_df = pd.DataFrame(employee_data)

display(employee_df.head())

    id   name department  managerId
0  101   John          A        NaN
1  102    Dan          A      101.0
2  103  James          A      101.0
3  104    Amy          A      101.0
4  105   Anne          A      101.0

In [ ]:
 df1 = df1.loc[df1[name_y >= '5']]

In [114]:
def find_managers(employee: pd.DataFrame) -> pd.DataFrame:
    df1 = employee
    df2 = employee
    final_df = pd.merge(left = df1, right = df2, how = 'inner',
    left_on = 'id', right_on = 'managerId')
    fc = final_df['managerId_x'].isnull()
    df1 = final_df[fc].groupby('name_x').agg({'name_y': 'count'}).reset_index()
    df1 = df1.rename(columns={'name_x':'name'})
    #df1 = df1['name_y']>=5  - gives series
    fc1 = df1['name_y']>=5
    return df1[fc1][['name']]

In [115]:
find_managers(employee_df)

   name
0  John

## Q8. Confirmation Rate - Case When in Python Solution (Important Question) - Refer to Github