<a href="https://colab.research.google.com/github/AkankshaB123/python/blob/main/Pandasdtypes_Series%26Pandas(Session12).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

In [4]:
os.getcwd()

'/content'

In [2]:
import pandas as pd

In [22]:
df = pd.read_csv("/content/drive/MyDrive/Advertising.csv", index_col=0)
df.head(5)

      TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

# **2 basic datatypes - DataFrame, Series**
### 1. **Data Frame** -  (mxn), m and n > 1 (m - row, n- column)
### 2. **Series** - (mxn) at least m or n is = 1
* Series - either a row or column

# Data Frame

In [24]:
type(df)

pandas.core.frame.DataFrame

# Series

In [26]:
type(df['Radio'])

pandas.core.series.Series

# Exploratory Data Analysis
### INFO COMMAND

# Summary

In [27]:
#summary
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB

# describe()

# Data Statistics

In [29]:
df.describe()

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

### Findings
* 200 records
* All these variables are roughly symmetrical (normally distributed) because 50% (P25th) = median.
* Standard deviation: TV ads std (highest), it varies a lot wrt sales - huge spread
### IQR = Q3 - Q1
* TV: 219-74 = 145
* Radio: 36-10 = 26
* Newspaper: 45-13 = 32
* Sales: 17-10 = 7
* Sales is more stable than ad budgets
### Outliers (IQR Strategy)
* Newspaper Upper bound = Q3 + 1.5*IQR
* 1.5*32 + 45 = 93
* Newspaper max = 114 (Outliers above 93)
-----------------------------
* Upper bound = Q3 + 1.5*IQR
* TV = 219 + 1.5*145 = 436
* TV's max = 296 (No outliers)

## Observations from the df.describe() function
* count
* mean
* std
* min & max
* 25% (P25th, first quartile/ Q1)
* 50% (P50th, median/Q2)
* 75% (P75th, third quartile/Q3)

* Distribution is skewed or not - that can be answered using percentile

In [6]:
df1 = pd.read_csv("/content/drive/MyDrive/100 Sales Records.csv")
df1.head(4)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82

In [7]:
df1.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+02,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02
mean,5.550204e+08,5128.710000,276.761300,191.048000,1.373488e+06,9.318057e+05,4.416820e+05
std,2.606153e+08,2794.484562,235.592241,188.208181,1.460029e+06,1.083938e+06,4.385379e+05
min,1.146066e+08,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03
25%,3.389225e+08,2836.250000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.214436e+05
50%,5.577086e+08,5382.500000,179.880000,107.275000,7.523144e+05,3.635664e+05,2.907680e+05
75%,7.907551e+08,7369.000000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.358288e+05
max,9.940222e+08,9925.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06

## Includes categorical column description as well!

In [9]:
df1.describe(include = 'all')

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,100,100,100,100,100,100,1.000000e+02,100,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02
unique,7,76,12,2,4,100,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN
top,Sub-Saharan Africa,The Gambia,Cosmetics,Offline,H,5/28/2010,NaN,11/17/2010,NaN,NaN,NaN,NaN,NaN,NaN
freq,36,4,13,50,30,1,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,5.550204e+08,NaN,5128.710000,276.761300,191.048000,1.373488e+06,9.318057e+05,4.416820e+05
std,NaN,NaN,NaN,NaN,NaN,NaN,2.606153e+08,NaN,2794.484562,235.592241,188.208181,1.460029e+06,1.083938e+06,4.385379e+05
min,NaN,NaN,NaN,NaN,NaN,NaN,1.146066e+08,NaN,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03
25%,NaN,NaN,NaN,NaN,NaN,NaN,3.389225e+08,NaN,2836.250000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.214436e+05
50%,NaN,NaN,NaN,NaN,NaN,NaN,5.577086e+08,NaN,5382.500000,179.880000,107.275000,7.523144e+05,3.635664e+05,2.907680e+05
75%,NaN,NaN,NaN,NaN,NaN,NaN,7.907551e+08,NaN,7369.000000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.358288e+05
max,NaN,NaN,NaN,NaN,NaN,NaN,9.940222e+08,NaN,9925.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06

* top - most popular
* freq - frequency of that occurrence
* Nan is expected in categorical & top, freq for numerical is expected with Nan